// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dom.proto

package dom_api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PaymentCallbackRequest struct {
	TransactionId        string   `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Amount               float32  `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Status               int32    `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentCallbackRequest) Reset()         { *m = PaymentCallbackRequest{} }
func (m *PaymentCallbackRequest) String() string { return proto.CompactTextString(m) }
func (*PaymentCallbackRequest) ProtoMessage()    {}
func (*PaymentCallbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_53fbabfbd232ed5a, []int{0}
}

func (m *PaymentCallbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentCallbackRequest.Unmarshal(m, b)
}
func (m *PaymentCallbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentCallbackRequest.Marshal(b, m, deterministic)
}
func (m *PaymentCallbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentCallbackRequest.Merge(m, src)
}
func (m *PaymentCallbackRequest) XXX_Size() int {
	return xxx_messageInfo_PaymentCallbackRequest.Size(m)
}
func (m *PaymentCallbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentCallbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentCallbackRequest proto.InternalMessageInfo

func (m *PaymentCallbackRequest) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

func (m *PaymentCallbackRequest) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *PaymentCallbackRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type PaymentCallbackResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentCallbackResponse) Reset()         { *m = PaymentCallbackResponse{} }
func (m *PaymentCallbackResponse) String() string { return proto.CompactTextString(m) }
func (*PaymentCallbackResponse) ProtoMessage()    {}
func (*PaymentCallbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53fbabfbd232ed5a, []int{1}
}

func (m *PaymentCallbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentCallbackResponse.Unmarshal(m, b)
}
func (m *PaymentCallbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentCallbackResponse.Marshal(b, m, deterministic)
}
func (m *PaymentCallbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentCallbackResponse.Merge(m, src)
}
func (m *PaymentCallbackResponse) XXX_Size() int {
	return xxx_messageInfo_PaymentCallbackResponse.Size(m)
}
func (m *PaymentCallbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentCallbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentCallbackResponse proto.InternalMessageInfo

func (m *PaymentCallbackResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*PaymentCallbackRequest)(nil), "dom.api.PaymentCallbackRequest")
	proto.RegisterType((*PaymentCallbackResponse)(nil), "dom.api.PaymentCallbackResponse")
}

func init() { proto.RegisterFile("dom.proto", fileDescriptor_53fbabfbd232ed5a) }

var fileDescriptor_53fbabfbd232ed5a = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0xc9, 0xcf, 0xd5,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x07, 0x31, 0x13, 0x0b, 0x32, 0x95, 0xf2, 0xb9, 0xc4,
	0x02, 0x12, 0x2b, 0x73, 0x53, 0xf3, 0x4a, 0x9c, 0x13, 0x73, 0x72, 0x92, 0x12, 0x93, 0xb3, 0x83,
	0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x54, 0xb9, 0xf8, 0x4a, 0x8a, 0x12, 0xf3, 0x8a, 0x13,
	0x93, 0x4b, 0x32, 0xf3, 0xf3, 0xe2, 0x33, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x78,
	0x91, 0x44, 0x3d, 0x53, 0x84, 0xc4, 0xb8, 0xd8, 0x12, 0x73, 0xf3, 0x4b, 0xf3, 0x4a, 0x24, 0x98,
	0x14, 0x18, 0x35, 0x98, 0x82, 0xa0, 0x3c, 0x90, 0x78, 0x71, 0x49, 0x62, 0x49, 0x69, 0xb1, 0x04,
	0xb3, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x94, 0xa7, 0x64, 0xcc, 0x25, 0x8e, 0x61, 0x61, 0x71, 0x41,
	0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x04, 0x17, 0x7b, 0x6e, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0x2a, 0xd4,
	0x2a, 0x18, 0xd7, 0x28, 0x89, 0x8b, 0xcb, 0xc5, 0xdf, 0x37, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39,
	0x55, 0x28, 0x84, 0x8b, 0x1f, 0xcd, 0x08, 0x21, 0x79, 0x3d, 0xa8, 0x87, 0xf4, 0xb0, 0xfb, 0x46,
	0x4a, 0x01, 0xb7, 0x02, 0x88, 0xed, 0x49, 0x6c, 0xe0, 0x90, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xf5, 0x63, 0xb8, 0x37, 0x26, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DOMServiceClient is the client API for DOMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DOMServiceClient interface {
	// create payment
	PaymentCallback(ctx context.Context, in *PaymentCallbackRequest, opts ...grpc.CallOption) (*PaymentCallbackResponse, error)
}

type dOMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDOMServiceClient(cc grpc.ClientConnInterface) DOMServiceClient {
	return &dOMServiceClient{cc}
}

func (c *dOMServiceClient) PaymentCallback(ctx context.Context, in *PaymentCallbackRequest, opts ...grpc.CallOption) (*PaymentCallbackResponse, error) {
	out := new(PaymentCallbackResponse)
	err := c.cc.Invoke(ctx, "/dom.api.DOMService/PaymentCallback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DOMServiceServer is the server API for DOMService service.
type DOMServiceServer interface {
	// create payment
	PaymentCallback(context.Context, *PaymentCallbackRequest) (*PaymentCallbackResponse, error)
}

// UnimplementedDOMServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDOMServiceServer struct {
}

func (*UnimplementedDOMServiceServer) PaymentCallback(ctx context.Context, req *PaymentCallbackRequest) (*PaymentCallbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PaymentCallback not implemented")
}

func RegisterDOMServiceServer(s *grpc.Server, srv DOMServiceServer) {
	s.RegisterService(&_DOMService_serviceDesc, srv)
}

func _DOMService_PaymentCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DOMServiceServer).PaymentCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dom.api.DOMService/PaymentCallback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DOMServiceServer).PaymentCallback(ctx, req.(*PaymentCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DOMService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dom.api.DOMService",
	HandlerType: (*DOMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PaymentCallback",
			Handler:    _DOMService_PaymentCallback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dom.proto",
}
